mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml, classpath:/mybatis/mapper/ex/*.xml
#  config-location:  classpath:/mybatis/config/mybatis-config.xml

spring:
  profiles:
    active: dev

server:
  port: 8083
